### PR TITLE
Fix license information so GitHub detects it correctly

### LINKED ISSUE #7: Github seems unable to detect this repo as Apache 2.0 licenced
GitHub doesn't see this repository as Apache 2.0 licensed. It would be awesome if this was fixed.

You can find out how license detection works at https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license

### PR DESCRIPTION
**Pull request by mithro**
Fixes #7 .

See the following screenshots;

Screenshot from 2020-01-14 14-43-49

Screenshot from 2020-01-14 14-45-08

### CODE REVIEW

**Comment by shioyadan** [comment]
Thanks for your fix. I was also wondering why the LICENSE file was not recognized correctly, but did not notice that there was an unnecessary blank line.

The THIRD-PARTY-LICENSES file is now empty, but we will update it in the near future as we add some benchmarks (ex. Core Mark) to the repository. So, could you recover it?

**Comment by mithro** [comment]
@shioyadan I think the detection is /actually/ getting confused by you having multiple files with `LICENSE` in the name. The recommended approach for including third party stuff into your project is to create a `third_party` directory and include the information under that. You can see how Google recommends their engineers organize repositories at https://opensource.google/docs/releasing/preparing/#third-party-components

**Comment by shioyadan** [comment]
Thank you for your explanation. I understand the situation. 
I will put third-party related files to another place.
I will merge your pull request soon.
Thanks!

**Comment by mithro** [comment]
@shioyadan Looks like it is all working now! Thanks.

**Pull request merged**
